start-django-proj-in-docker:
	docker compose run --rm web-app sh -c "django-admin startproject service ."

docker-commands:
	docker rmi $(docker images -a -q)
	docker rm -f $(docker ps -a -q)
	docker volume prune
	#docker compose -f docker-compose.local.yaml down --volumes

	#docker volume ls
	#docker ps -a
	#docker images

docker-migrate:
	docker compose run --rm web-app sh -c "python manage.py migrate"

docker-create-superuser:
	docker compose run --rm web-app sh -c "python manage.py createsuperuser"
