start-django-proj-in-docker:
	docker compose run --rm web-app sh -c "django-admin startproject service ."

start-django-app-in-docker:
	docker compose run --rm web-app sh -c "python manage.py startapp clients"

docker-commands:
	docker rmi $(docker images -a -q)
	docker rm -f $(docker ps -a -q)
	docker volume prune
	#docker compose -f docker-compose.local.yaml down --volumes

	#docker volume ls
	#docker ps -a
	#docker images

docker-migrations:
	docker compose run --rm web-app sh -c "./manage.py makemigrations clients"
	docker compose run --rm web-app sh -c "python manage.py migrate"

docker-create-superuser:
	docker compose run --rm web-app sh -c "python manage.py createsuperuser"

docker-connect-django-shell-for-work-with-a-Django-project-from-the-command-line-to-run-queries-and-test-code-snippets:
	docker compose run --rm web-app sh -c "python manage.py shell"

